### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by sitaram-gupta** [nameisjayant/MVVM-DaggerHilt-Retrofit-Sealed-Class-StateFlow-Coroutines-In-Android#1]
Hi,
Thanks for the ease way of making amazing tutorials. Love from Nepal .
I just clone and run the app but app is getting crash:
Logs:
`2021-06-10 14:41:10.608 20794-20794/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.demo, PID: 20794
    java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Platform.get(Platform.java:85)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202)
        at retrofit2.Retrofit$Builder.build(Retrofit.java:614)
        at com.example.demo.di.AppModule.providesApiService(AppModule.kt:25)
        at com.example.demo.di.AppModule_ProvidesApiServiceFactory.providesApiService(AppModule_ProvidesApiServiceFactory.java:30)
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC.apiService(DaggerBaseApp_HiltComponents_SingletonC.java:64)
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC.access$1800(DaggerBaseApp_HiltComponents_SingletonC.java:44)
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl.apiServiceImpl(DaggerBaseApp_HiltComponents_SingletonC.java:317)
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl.mainRepository(DaggerBaseApp_HiltComponents_SingletonC.java:321)
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl.mainViewModel(DaggerBaseApp_HiltComponents_SingletonC.java:325)
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl.access$1900(DaggerBaseApp_HiltComponents_SingletonC.java:309)
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl$SwitchingProvider.get(DaggerBaseApp_HiltComponents_SingletonC.java:354)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:98)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84)
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:107)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.example.demo.MainActivity.getMainViewModel(Unknown Source:2)
        at com.example.demo.MainActivity.onCreate(MainActivity.kt:28)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.internal.platform.Platform.get(Platform.java:85) 
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:202) 
        at retrofit2.Retrofit$Builder.build(Retrofit.java:614) 
        at com.example.demo.di.AppModule.providesApiService(AppModule.kt:25) 
        at com.example.demo.di.AppModule_ProvidesApiServiceFactory.providesApiService(AppModule_ProvidesApiServiceFactory.java:30) 
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC.apiService(DaggerBaseApp_HiltComponents_SingletonC.java:64) 
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC.access$1800(DaggerBaseApp_HiltComponents_SingletonC.java:44) 
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl.apiServiceImpl(DaggerBaseApp_HiltComponents_SingletonC.java:317) 
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl.mainRepository(DaggerBaseApp_HiltComponents_SingletonC.java:321) 
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl.mainViewModel(DaggerBaseApp_HiltComponents_SingletonC.java:325) 
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl.access$1900(DaggerBaseApp_HiltComponents_SingletonC.java:309) 
        at com.example.demo.di.DaggerBaseApp_HiltComponents_SingletonC$ActivityRetainedCImpl$ViewModelCImpl$SwitchingProvider.get(DaggerBaseApp_HiltComponents_SingletonC.java:354) 
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:98) 
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69) 
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:84) 
        at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:107) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54) 
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41) 
        at com.example.demo.MainActivity.getMainViewModel(Unknown Source:2) 
        at com.example.demo.MainActivity.onCreate(MainActivity.kt:28) 
        at android.app.Activity.performCreate(Activity.java:8000) 
        at android.app.Activity.performCreate(Activity.java:7984) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
`

**Comment by sitaram-gupta** [comment]
It does smoothly run on SDK 28 but not in 30.
How can i also make run for SDK 30?

**Comment by sitaram-gupta** [comment]
I added okHttp dependency and it worked like charm!
